# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.2
yarn_mappings=26.2+build.1
loader_version=0.19.3

# Mod Properties
mod_version=0.1.0
maven_group=com.example
archives_base_name=autobuilder

# Dependencies
fabric_version=0.152.0+26.2
malilib_version=26.2-0.29.3
litematica_version=26.2-0.28.4
